In [1]:
#.1.Ans :-
import numpy as np
l = [1,2,3,'HGF',['2.45',6]]

In [2]:
type(l)

list

In [3]:
l1 = ['hgdff','gfd','kjg']

In [4]:
arr = np.array(l1)

In [5]:
arr

array(['hgdff', 'gfd', 'kjg'], dtype='<U5')

In [6]:
# Basci diff is list can be nested, but array can not take nested list. List element of different 
# datatype, but array contains same data type.

In [7]:
arr.dtype

dtype('<U5')

In [8]:
# Ans.2:
for i in arr:
    print(i)

hgdff
gfd
kjg


In [9]:
for i in l1:
    print(i)

hgdff
gfd
kjg


In [10]:
l1 = ['dfg','fgh']

In [49]:
type(l1)

list

In [11]:
#.Ans.3:-
num_list = [[1,2,3],[4,5,6]]

In [12]:
num_array = np.array(num_list)

In [13]:
num_list

[[1, 2, 3], [4, 5, 6]]

In [14]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
for i in num_list:
    for j in i:
        print(j, end="")
    print()

123
456


In [20]:
def test(a):
    n = []
    for i in a:
        if type(i) == list:
            for j in i:
                if type(j) == int:
                    n.append(j)
        else:
            if type(i) == int:
                n.append(i)
    return(n)           

In [21]:
test(num_list)

[1, 2, 3, 4, 5, 6]

In [28]:
num_array[0][0]

1

In [30]:
for i in num_array:
    for j in i:
        print(j, end=" ")
    print()

1 2 3 
4 5 6 


In [32]:
#.Ans.4:-
np.shape(num_array)

(2, 3)

In [33]:
np.size(num_array)

6

In [35]:
#Ans.5:-
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [38]:
#Ans.6:-
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])